modLoader="javafml"
loaderVersion="[47,)"
license="CC0-1.0"

[[mods]]
modId="stardewhud"
version="1.2.0-forge"
displayName="StardewHUD"
description='''一个星露谷物语风格的HUD模组，可显示时间、天气、运势和物品计数器'''
authors="Weatheraintbad"
logoFile="assets/stardewhud/icon.png"

[[dependencies.stardewhud]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="BOTH"

[[dependencies.stardewhud]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.21)"
ordering="NONE"
side="BOTH"